### ISSUE TITLE
Feature request: add links between containers [REPLACE DOCKER COMPOSE]

### ISSUE THREAD

**Issue by OnkelTem** [dnephin/dobi#103]
I'm very new to Dobi and considering some possibilities to start using it in one of my projects.

My current setup includes **docker-compose** and a set of bash scripts to automate starting up/shutting down my containers as well as performing some maintenance tasks. The difficult part for me is to decide what remains for **docker-compose**+scripts and what goes into **dobi**.

I realize that this comment is kind of premature as I'm going to report only one problem at this moment while new ones would follow. Nevertheless I'm adding a loud tag into the title of this thread - [REPLACE DOCKER COMPOSE] - to accent on the main approach - why using both after all? So let me state it clear: I want to build my solution totally on Dobi. I personally feel some refusal at the idea of mating one front-end **Dobi** with another - **docker-compose** as you have to split the logic into two not-related parts with different architecture, and then you have to maintain those two things separately and update two tools, and wahtsoever... That's bad.

Now to the subject. In `docker-compose.yml` I can do:

```
  web:
    links: [db:dbhost, mail:mailhost]
    #...

  db:
    #...

  mail:
    #...
```

and appropriate links would be added to `/etc/hosts` of the `web` container, as well as dependencies  applied. Now I want to see the similar functionality in Dobi. 

Do you approve such an approach [of thinking]?

**Comment by dnephin** [comment]
I think each tool has a different focus, and that they actually compliment each other pretty well.

`docker-compose` is, as it's described in the docs: "a tool for defining and running multi-container Docker applications". Some important things to note about this description is mentions only "running", not building. It happens to have some basic support for building images, but not much else.

In practice this means if you have a "stack" of services (ex: web, db, task queue, mail server, cache, etc) that are all necessary for some functionality then a Compose file is the right solution. You can `up` and `down` the stack as a single unit, they all join the same network, etc. `docker-compose` is exactly what you want for creating a development environment or an isolated test environment for end-to-end testing.

`dobi` on the other hand is for building the application. It defines tasks like building binaries, Docker images, running tests, running code linting, running code generation, building docs etc. One such task might be to create a dev environment, or run e2e tests, so it makes sense that `dobi` can launch `docker-compose` for this purpose, but I don't think it would replace the functionality. You could, for example, have `dobi` build all the images, then use them in a Compose file for running the environment. 

`dobi` also handles things like running a container to generate an environment variable that can be injecated into a container or a Compose file. 

I think this distinction between behaviour is valuable and helps keep both tools focused and easier to understand.

> Now I want to see [links] in Dobi.

Links has been deprecated and unnecessary for a long time now. Compose kept them for backwards compatibility, but you don't actually need to use them. All the containers in a Compose file will joined to a network created by Compose, so they can communicate without links using the same name.

This functionality already exists in `dobi`. You can use `net-mode:` on a job to join a specific network. You can see this in the [init-db-with-rails example dobi.yaml](https://github.com/dnephin/dobi/blob/master/examples/init-db-with-rails/dobi.yaml#L45-L46) where a job joins a network created by compose.

I'd like to expand on this behaviour and have a `network` resource, as well as a `networks:` section for a job to support joining multiple networks, but it haven't been a priority just yet.

I hope that helps explain things. I should add this to the docs as well.

**Comment by OnkelTem** [comment]
Then I don't really understand how can I use Dobi. You see it was recommended in one discussion as a solution to a problem I had with my docker-compose setup.

Let me describe it shortly.

There is a web application which includes two containers - web and db. There are also some CLI-tools which are used to perform different maintenance tasks against web-container's file system. If we place them into the web container it would be a fat one which is a bad thing by itself. So we isolate them into an additional container - tools. But now comes the problem: they are not services, they are tasks. There isn't a main process which would be running during the application instance's life cycle. So I can't really use this image with docker-compose as a service, right? I can't even declare it in docker-compose to get image fetched or executed.

Now when I think how would I use Dobi to run this tool-image, I see that I would have to repeat all the configuration I already have in `docker-compose.yml` but now in `dobi.yaml`. Say if I had 10 mounts in there, now I have to repeat them from scratch (and maintain this list separately). That of course is not acceptable. The same concerns environment variables, network mode, hosts declaration and whatsoever.

The only workaround I see for now - is to create that tool-image with a fake long-running process. And judging from what I see in the Internet - a lot of people do this crap.

**Comment by dnephin** [comment]
> Now when I think how would I use Dobi to run this tool-image, I see that I would have to repeat all the configuration I already have in docker-compose.yml

No. Did you look at the example I linked? It is exactly what you describe.

**Comment by OnkelTem** [comment]
> No. Did you look at the example I linked? It is exactly what you describe.

Yes, but how is it related?

**Comment by dnephin** [comment]
Tasks go into `dobi.yaml`, services go into `docker-compose.yaml`. When a job task needs to communicate with a service it can join the network by using `net-mode: ...` to join the default network created by Compose.

I don't see any duplication.

**Comment by OnkelTem** [comment]
> When a job task needs to communicate with a service it can join the network by using net-mode: ... to join the default network created by Compose.

Do mean ssh-ing between services? That's not needed, and moreover - this is not the main use of the service when you perform maintenance tasks. Such tasks as installing composer/node/ruby packages, building CSS/JS and etc - operate on the same filesystem as the service container use. Mounts, which your services use for their works are also needed for such tasks. If I declare such a task inside Dobi, then I should duplicate each and every such a mount from docker-compose.

**Comment by dnephin** [comment]
>  If I declare such a task inside Dobi, then I should duplicate each and every such a mount from docker-compose.

Not necessarily. You might have a single mount `.:/code`, or you might just built the results into an image and run the image from the compose file.

**Comment by OnkelTem** [comment]
> Not necessarily. You might have a single mount .:/code, 

This is a sort of misrepresenting of a problem because I stated that there are several mounts while you've replaced this with one single mount. As I said, there are initially several mounts - for custom code, for libraries, there are also mounts for configs and database. 

> or you might just built the results into an image and run the image from the compose file.

It's not a matter of building something just one time. I was saying about maintenance tasks which are  executed regularly against project files.

**Comment by dnephin** [comment]
It doesn't matter how many times you build, you configure it once.

**Comment by OnkelTem** [comment]
> It doesn't matter how many times you build, you configure it once.

Sorry, I don't really understand what you're saying now...

**Comment by dnephin** [comment]
You said

> I was saying about maintenance tasks which are executed regularly against project files.

But I don't understand why that matters, because everything is configured as a task, so it doesn't matter how many times you execute a task.

Getting back to the original question/issue: In the short term a feature like  #45,might be what you're looking for.  In the long term maybe `dobi` could support stacks using the code in `docker/cli`, so that `docker-compose` the tool wouldn't be necessary, but you could still use Compose files.

**Comment by dnephin** [comment]
I'm going to close this issue since there are already two issues open for the planned "service" and "stack" features (#45, #92).
