### ISSUE TITLE
Support variables interpolation for mount.bind

### ISSUE THREAD

**Issue by OnkelTem** [dnephin/dobi#113]
According to documentation variables interpolation isn't supported. I wonder why this is so?

**Comment by dnephin** [comment]
Since `mount.bind` is a relative path on the host I haven't found a use case yet that required it to support variables yet. I've been trying to only add variables to fields as they are needed.

Do you have a use case that requires it to support variables?

**Comment by OnkelTem** [comment]
Yes, sure. Imagine that `git clone someurl <project>` command is wrapped into a docker container. So that you could run it with random destination.

Here comes two problems:

1) There is no way to pass <project> directly, instead with should use environment variable:

```
$ PROJECT=project dobi fetch-project
```

2) It's not gonna interpolate that:

```yaml
  mount=project-destination
    bind: ./proejects/{$PROJECT}
    path: /workdir
```

**Comment by dnephin** [comment]
I've updated this issue to be a feature request. Would you be interested in adding it? The changes needs to be made here: 

https://github.com/dnephin/dobi/blob/692a02f32162d8e59894c8c9a2f181b1b74ec714/config/mount.go#L98-L112

by adding another `resolver.Resolve`. The resolved value would need to be passed to `fs.ExpandUser()` before storing it on `conf.Bind`.

and the docs are here: https://github.com/dnephin/dobi/blob/692a02f32162d8e59894c8c9a2f181b1b74ec714/docs/source/variables.rst

**Comment by OnkelTem** [comment]
Daniel, do you that I can update the docs?

**Comment by dnephin** [comment]
I'm asking if you would be interested in making the code change, and also update the docs.
