### ISSUE TITLE
Can't stop tasks by Ctrl-C

### ISSUE THREAD

**Issue by OnkelTem** [dnephin/dobi#117]
Giving one more chance for Dobi on one of my projects...

I can't stop any job task with Ctrl-C. Tried different tasks, also tried `interactive` property w/o luck. Ideas?

**Comment by dnephin** [comment]
You will definitely need `interactive`, it wont work without it. I often kill my long running tasks with `ctrl-c`, as long I use interactive, it works, which  is why I think #90 is probably a good idea.

**Comment by dnephin** [comment]
If it's not working it could be that the process in the container is not doing the right thing when it receives SIGINT. You can try with a dummy program that just prints the signal then exits, to see if it receives sigint.

**Comment by OnkelTem** [comment]
I confirm it works. Thanks. For some reason one task didn't want to exit in `interactive` mode.
