### ISSUE TITLE
0.11 release 

### ISSUE THREAD

**Issue by cescoferraro** [dnephin/dobi#130]
the new release seems to be broken. i will try to take a look at #74 today, its really holding me back.

![011](https://user-images.githubusercontent.com/6259987/39048734-dc5b422e-4474-11e8-8bd4-78600656d55a.png)

**Comment by dnephin** [comment]
It seems like `dobi` continued to use the same version of `Gotty`, but maybe some other dependency changed which caused this issue. Either way I think i'll fork that library and add a fix.

**Comment by dnephin** [comment]
I tagged `v0.11.1` with the fix
