### ISSUE TITLE
git clone git@github.com:dnephin/dobi failed

### ISSUE THREAD

**Issue by d3netxer** [dnephin/dobi#154]
```
$ git clone git@github.com:dnephin/dobi
Cloning into 'dobi'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by dnephin** [comment]
This is not an issue with the dobi repo. It seems to be an issue with the SSH key you have setup with github.

If you don't have an SSH key, or it's not working, you can always use the HTTPS url: https://github.com/dnephin/dobi.git
