### ISSUE TITLE
The build time of image with inline dockerfile

### ISSUE THREAD

**Issue by sih4sing5hong5** [dnephin/dobi#164]
https://github.com/dnephin/dobi/blob/988d67bafdbccc18dbd323cf036fae3d2a665155/config/image.go#L15-L18

Should the docs  mention this?
```
If using inline Dockerfile, the **dobi.yaml** file will be considered as a part of the build context.
```

**Comment by dnephin** [comment]
Yes, I think that would be a good addition to the docs

**Comment by sih4sing5hong5** [comment]
Done
