### ISSUE TITLE
How to use runtime=nvidia in dobi?

### ISSUE THREAD

**Issue by sih4sing5hong5** [dnephin/dobi#166]
There two ways for using [nvidia-docker](https://github.com/NVIDIA/nvidia-docker#nvidia-container-runtime-for-docker), setting `runtime` or using another command `nvidia-docker`.

1. `docker run --runtime=nvidia [image] ...` 
  - https://github.com/NVIDIA/nvidia-docker/wiki/Usage#nvidia-runtime
2. nvidia-docker run [image] ...

Which one is more compatiable with dobi?

**Comment by sih4sing5hong5** [comment]
The host config of `Runtime` is at [fsouza/go-dockerclient](https://github.com/fsouza/go-dockerclient/blob/95cf5057430071fc9c804a15ce36884474d4112e/container.go#L787).
The host settings of dobi are at [tasks/job/run.go](https://github.com/dnephin/dobi/blob/4876d2d810f231657f6c0345ba4074a83ad5caac/tasks/job/run.go#L274).

**Comment by sih4sing5hong5** [comment]
I know I should insert `Runtime : t.config.Runtime` into [run.go](https://github.com/dnephin/dobi/blob/4876d2d810f231657f6c0345ba4074a83ad5caac/tasks/job/run.go#L274).

But how to keep runtime as default if user doesn't set this `runtime` variable?

**Comment by dnephin** [comment]
I guess there is no way to set that as a default for all jobs right now.

**Comment by sih4sing5hong5** [comment]
This problem is solved after docker 19.03. Because the docker runtime supports [the nvidia GPU](https://github.com/NVIDIA/nvidia-docker#quickstart).

Thank you for this great work!
