### ISSUE TITLE
Is possible set cpu limit for a job?

### ISSUE THREAD

**Issue by sih4sing5hong5** [dnephin/dobi#169]
The docker can limit the CPU resource for a container by `--cpus=2.5`.
How to set this limit with `dobi`?

Thank you!

**Comment by dnephin** [comment]
It is not possible yet. It would require adding a field to the `job` resource and passing it through here: https://github.com/dnephin/dobi/blob/master/tasks/job/run.go#L256-L281

**Comment by sih4sing5hong5** [comment]
Thank you! 
May I make a PR for this field?

**Comment by dnephin** [comment]
Yes please, that would be great, thank you!

**Comment by sih4sing5hong5** [comment]
Thank you for providing where the code is. The functions is not necessary for now. Close this issue.
