### ISSUE TITLE
Chocolatey package for installing on Windows

### ISSUE THREAD

**Issue by flcdrg** [dnephin/dobi#175]
I've created a Chocolatey package to enable installing dobi on Windows using the [Chocolatey package manager](https://chocolatey.org).

Once the package has been moderated/approved, it will be visible at https://chocolatey.org/packages/dobi. I could submit a PR to add info to the install instructions if that would be useful.

If you'd ever like to take over maintaining the package, let me know.

**Comment by dnephin** [comment]
Thank you for creating the package! A PR to add a link to the Chocolatey install would be great.
