### ISSUE TITLE
glob patterns for sources and artifacts

### ISSUE THREAD

**Issue by mlilien** [dnephin/dobi#192]
Is it possible to exclude files/directories from sources resp. artifacts?
I would like to achive something like.
```
sources:
  - "./"
  - "!./dirA/"
```

**Comment by dnephin** [comment]
The glob pattern matching is documented here: https://golang.org/pkg/path/filepath/#Match.

I don't think there is any way to have some lines exclude patterns already matched by the first.

**Comment by mlilien** [comment]
thank you for clarifying.
