### ISSUE TITLE
[feature] Command to list images/jobs, not just aliases

### ISSUE THREAD

**Issue by wittekm** [dnephin/dobi#199]
Hi! `dobi list` only shows aliases; it'd be super convenient if there were a `dobi list job` or `dobi list image` type thing :)

I might try and contribute this on my own, just wanted to get an opinion on it first.

**Comment by dnephin** [comment]
It should list all of the resources, not just aliases. You may need `--all` , because it will default to excluding any that do not have descriptions.

**Comment by wimax-grapl** [comment]
> It should list all of the resources, not just aliases. You may need `--all` , because it will default to excluding any that do not have descriptions.

Ah, good call! Thanks! We can close this out then
