### ISSUE TITLE
Subprojects cannot use mounts from the parent.

### ISSUE THREAD

**Issue by deinspanjer** [dnephin/dobi#20]
They seem to silently fail to do the mount.

**Comment by dnephin** [comment]
I couldn't find any issues with the mounts in your example, the only problem I found was the build context. Once I changed the build context it worked.

I created #22 for the change I think that is required to make subprojects work. For now paths have to be relative to the root `dobi.yaml`

**Comment by dnephin** [comment]
I think the issue here is covered by #22, so I'm going to close this issue. If  there are other problems, please comment again and I'd be happy to re-open this issue.
