### ISSUE TITLE
build dependencies with no cache

### ISSUE THREAD

**Issue by ryanfraserRGA** [dnephin/dobi#202]
Hey there,  I've been evaluating dobi for a project I'm working on, and it my current top candidate of what's out there.  Defining image dependencies has been really quite a wonderful thing.  My main question (and if this is not the right place for it, I apologize ahead of time) is this: Is there a way to force image builds with no-cache?  I have a base image that doesn't change very often and therefore will remain cached.  However, in the event a yum package were to be updated, there would be no way for docker to detect this as we don't have versions hard coded in our base image.  If this is a silly question that I overlooked the answer in the documentation, I apologize ahead of time.

**Comment by dnephin** [comment]
I don't think there is any way to set no-cache right now. Maybe an env var to set that would be good.

You can always break the cache by adding an `ENV breakthecache=1` to the Dockerfile before the line you want to rebuild, but that's not very convenient.

**Comment by ryanfraserRGA** [comment]
Thanks for the feedback, that might be a little kludgey for me to sell to the team.  Would love to see a configuration flag in the future or a way to pass additional build options through the dobi yaml.  Either way, thanks for the great work.
