### ISSUE TITLE
Provide arm binaries

### ISSUE THREAD

**Issue by cescoferraro** [dnephin/dobi#47]
I think it would be nice if we could provide arm binaries for the next release.
Gox does not support all arm arch, as of right [now](https://github.com/Masterminds/glide/pull/528)
It think you know that. I have used https://github.com/franciscocpg/gox lately and it works great. 

We just need to change this dep

https://github.com/dnephin/dobi/blob/master/dockerfiles/Dockerfile.build#L16

But the build script need a little change

https://github.com/dnephin/dobi/blob/master/script/build#L7

Maybe

```
gox \
    -ldflags "-X github.com/dnephin/dobi/cmd.gitsha=$gitsha \
              -X \"github.com/dnephin/dobi/cmd.buildDate=$builddate\"" \
    -output="/go/bin/dobi-{{.OS}}/{{.Arch}}" \
    -arch="amd64 armv5 armv6 armv7" -os="$oslist"   \
    .
```

**Comment by dnephin** [comment]
I think providing `arm` binaries would be good.

Do you actually have a need for all of those versions? I'd rather not generate a bunch of binaries that no one is going to use. It will just add clutter to the releases page.

Maybe
```
-output="/go/bin/dobi-{{.OS}}-{{.Arch}}"
-osarch-list="..."
```

**Comment by cescoferraro** [comment]
@dnephin 
I use dobi on the Raspberry PI. I would need at least armv6 and armv7. 
Armv5 is for the earlier models· Would not $DOBI_BUILD_OS become useless with -osarch-list ?

**Comment by dnephin** [comment]
Ok, what does the current `arm` give you? just v7?

`OSARCH` is necessary because we don't want to build every os * arch combination.  

`DOBI_BUILD_OS` can change to accept an `os/arch` pair instead.

**Comment by cescoferraro** [comment]
current arm return just v7 @dnephin

**Comment by acwatkins** [comment]
I could use this as well. I managed to build on the latest by changing amd64 to arm64 on my amd64 machine. So, gox is working out of the current image just fine now.
