### ISSUE TITLE
CI Linter

### ISSUE THREAD

**Issue by cescoferraro** [dnephin/dobi#61]
My box 
```
cescoferraro@desktop: ~/code/go/src/github.com/dnephin/dobi on feature/dobifile [?]
$ go run main.go lint
Step 1 : FROM golang:1.7-alpine
....
[check-merge-conflict] Check for merge conflicts.........................Passed
[end-of-file-fixer] Fix End of Files.....................................Passed
[trailing-whitespace] Trim Trailing Whitespace...........................Passed
[check-yaml] Check Yaml..................................................Passed
[check-json] Check JSON..............................(no files to check)Skipped
[go-fmt] go fmt..........................................................Passed
[go-lint] go lint........................................................Passed
[go-vet] go vet..........................................................Passed
[job: lint] Done
```

But my last builds have been sequentially failing to lint for those reasons.

```
tasks/task/stack.go:32:29: error strings should not be capitalized or end with punctuation or a newline
utils/fs/expanduser.go:25:27: error strings should not be capitalized or end with punctuation or a newline
```

A quick search shows that dobi has got quite a few of them.I have fixed the first one on the photo

![dobilint](https://cloud.githubusercontent.com/assets/6259987/20465059/ea61a11c-af3b-11e6-8e2b-5d66eca651eb.png)

**Comment by cescoferraro** [comment]
have you considered using https://godoc.org/github.com/pkg/errors ?
it would be cool if dobi -v could print the error stack trace

**Comment by cescoferraro** [comment]
maybe there is also something with git://github.com/dnephin/pre-commit-golang
because I should be catching those lint errors locally too

**Comment by dnephin** [comment]
`pkg/errors` would be a nice addition. I also didn't know about it until recently.

By default `pre-commit` will only run on files that are edited in the commit. So I think the `dobi lint` comamnd might be wrong. It should run with `-a` for all files I think.

**Comment by dnephin** [comment]
I just checked, and `pre-commit` is being run with `-a`. 

I'm not sure why your editor is complaining about those, but `golint` seems to be ok with it. Maybe `golint` has behaviour that I don't expect.

Using `pkg/errors` is still a good idea I think.

**Comment by dnephin** [comment]
#86 improves the linter by using gometalinter.
