### ISSUE TITLE
Proposal: compose hooks

### ISSUE THREAD

**Issue by willseward** [dnephin/dobi#68]
This is less of a proposal and more of a request for comments.

From what I can tell, dobi is the answer to a lot of questions I had about using Docker with compiled languages. I couldn't figure out a clean way to create builder Dockerfiles and still use Compose the way I wanted to.

What do y'all think about making a PR to docker compose to include build hooks to run dobi tasks before `up`?

Ex (in v1 for brevity):

```text
# docker-compose.yml
app:
   image: example/hello
   hooks:
       before_up: dobi dist-img
```

```text
# dobi.yml
image=builder:
    image: minimal-dev
    context: .
    dockerfile: Dockerfile.build

job=binary:
    use: builder
    artifact: ./dist/bin/hello
    mounts: [source, dist]
    description: "Build the static binary"

image=dist-img:
    image: example/hello
    dockerfile: Dockerfile.dist
    tags: ['{user.name}']
    depends: [binary]
    description: "Build the distribution image"
```

With the above, all would be required of the developer would be a `docker-compose up`. DC would call out to dobi for a build, and then run the appropriate image.

**Comment by dnephin** [comment]
I think it makes a lot more sense to go the other way.


```yaml

# dobi.yaml from above, with this addition

compose=up:
  files: [docker-compose.yaml]
  project: '{project}'
  depends: [dist-img]

```

Run `dobi up` to start the compose environment. 

I think it makes more sense to have the "generic build task tool" (dobi) driving all the tasks, instead of compose, which is only designed to start isolated environments.

That way all your commands are:

```
dobi binary
dobi test
dobi lint
dobi up
# etc
```

**Comment by willseward** [comment]
I agree with you. I didn't see the compose task...
