### ISSUE TITLE
Run task as non-root

### ISSUE THREAD

**Issue by tedstirm** [dnephin/dobi#7]
Is there any way to get a Run task to execute as non-root? Currently, there doesn't appear to be a way to set the user for the run task like you can with docker via the `-u` command. I have tried setting the USER value in my Dockerfile but the run task still seems to execute as root.

**Comment by dnephin** [comment]
Setting `USER` in the Dockerfile should work.

I think we should also add a `user:` field to http://dnephin.github.io/dobi/config.html#run so that you can set it for each run task.

**Comment by tedstirm** [comment]
You are correct `USER` does work as expected, there was a misunderstanding on my part. A `user:` would be a great addition.
