### ISSUE TITLE
Watch Resource

### ISSUE THREAD

**Issue by cescoferraro** [dnephin/dobi#72]
I havent used that many build tools. But tools like gulp/webpack/grunt all have the concept of watching the source code for changes and reacting to it. I have been noticing this patterns in all dobi projects I have been working on lately. 

I think dobi could offer a way for us to have better control over this process and avoid unnecessary files.
I have been using https://github.com/cespare/reflex which it has proven to be the fastest cross platform go implementation and on top of that you could spun multiple watchs task with different reaction commands by simply creating a text file. If I could make a PR to make reflex read from a stdout pipe instead of an actual file this should be easy to implement. 

We would also need a way to download the right reflex binary into whatever image the user want to use, or maybe make it a requirement, then check if the image contains reflex on the path at runtime before proceeding watching the files.

```
// This resource would run  `go run` whernever a .go file changes, 
// as well as running `node server.js` whenever any .tsx  or 
// ends with .config.js change
watch=dev:
    use: cescoferraro/project:development
    reflex:
      - global: '*.config.js'
        regex: '\.tsx'
        cmd: node server.js
      - regex: '\.go'
        cmd: go run main.go
```

**Comment by dnephin** [comment]
I think this can be done with a `job` and `image` resource in the current version.

If we make a top level `watch` resource, it would probably be integrated as go code, instead of a container. However the methods for watching code can vary by platform.

Keeping it in a container is nice, because it lets users continue to use gulp/grunt in a container, and not worry about learning the new syntax.

**Comment by dnephin** [comment]
I think we should support this with a regular `job` resource, which allows users to run whatever they want in a container. Many languages already have standard tools for doing this.

`dobi` shouldn't replace build tools like gulp/webpack/grunt. It's just a way of providing the necessary docker resources for those tools to run consistently and in different environments.
